# Generated by Django 3.0.5 on 2020-04-28 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zavod', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='klub',
            name='popis',
            field=models.TextField(blank=True, null=True, verbose_name='Popis'),
        ),
        migrations.AddField(
            model_name='klub',
            name='sidlo',
            field=models.CharField(max_length=45, null=True, verbose_name='Sidlo klubu'),
        ),
        migrations.AlterField(
            model_name='klub',
            name='nazev',
            field=models.CharField(max_length=45, unique=True, verbose_name='Nazev klubu'),
        ),
    ]
