# Generated by Django 3.0.5 on 2020-04-28 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zavod', '0002_auto_20200428_1302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='klub',
            old_name='nazev',
            new_name='name',
        ),
    ]
