# Generated by Django 3.0.5 on 2020-04-28 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zavod', '0003_auto_20200428_1351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='klub',
            old_name='name',
            new_name='nazev',
        ),
    ]
