# Generated by Django 3.0.5 on 2020-04-28 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zavod', '0004_auto_20200428_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klub',
            name='nazev',
            field=models.CharField(help_text='Zadej nazev klubu', max_length=45, unique=True, verbose_name='Nazev klubu'),
        ),
    ]
