# Generated by Django 3.0.5 on 2020-04-28 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zavod', '0005_auto_20200428_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='klub',
            name='popis',
        ),
        migrations.RemoveField(
            model_name='klub',
            name='sidlo',
        ),
    ]
