# Generated by Django 3.0.5 on 2020-04-28 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zavod', '0007_auto_20200428_1425'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='klub',
            options={'ordering': ['nazev']},
        ),
        migrations.RemoveField(
            model_name='klub',
            name='popis',
        ),
        migrations.RemoveField(
            model_name='klub',
            name='sidlo',
        ),
    ]
