# Generated by Django 3.0.5 on 2020-04-28 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zavod', '0009_auto_20200428_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='zavodnik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=45, unique=True, verbose_name='Jmeno zavodnika')),
            ],
            options={
                'ordering': ['jmeno'],
            },
        ),
    ]
