# Generated by Django 3.0.5 on 2020-04-28 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zavod', '0011_auto_20200428_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zavodnik',
            name='jmeno',
            field=models.CharField(max_length=45, null=True, verbose_name='Jmeno zavodnika'),
        ),
    ]
