# Generated by Django 3.0.5 on 2020-04-28 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zavod', '0013_zavod'),
    ]

    operations = [
        migrations.CreateModel(
            name='kategorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev_kategorie', models.CharField(help_text='Zadej nazev kategorie', max_length=45, unique=True, verbose_name='Nazev kategorie')),
                ('vek', models.CharField(max_length=45, null=True, verbose_name='Věk')),
                ('delka', models.IntegerField(blank=True, help_text='Delka tretě', null=True)),
                ('start', models.DateField(blank=True, null=True, verbose_name='Start zavodu')),
            ],
            options={
                'ordering': ['nazev_kategorie'],
            },
        ),
    ]
