# Generated by Django 3.0.5 on 2020-04-28 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zavod', '0014_kategorie'),
    ]

    operations = [
        migrations.CreateModel(
            name='partneri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev_partnera', models.CharField(max_length=45, unique=True, verbose_name='Nazev partnera')),
                ('popis_partnera', models.TextField(blank=True, null=True, verbose_name='Popis')),
            ],
            options={
                'ordering': ['nazev_partnera'],
            },
        ),
    ]
